### ISSUE TITLE
Address type added two times

### ISSUE THREAD

**Issue by phiren** [chrischen-melb/SPGooglePlacesAutocomplete#26]
In file SPGooglePlacesAutocompleteUtilities.m, address type added two times 
[names insertObject:@"address" atIndex:SPPlaceTypeAddress];

Due to it when try to search only cities, it returns regions data.

**Comment by chrischen-melb** [comment]
this repo is deprecated in favor of [Place Autocomplete in Google Places API for iOS](https://developers.google.com/places/ios-api/autocomplete)
